# Generated by Django 4.2.1 on 2023-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesters',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
