# Generated by Django 4.2.1 on 2024-01-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_alter_courses_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertls', models.CharField(max_length=250)),
                ('stats', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationProfile',
        ),
    ]
