# Generated by Django 4.2.1 on 2024-02-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_random_delete_registrationprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='random',
            old_name='alertls',
            new_name='alerts',
        ),
    ]
