# Generated by Django 4.2.1 on 2024-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_rename_alertls_random_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random',
            name='alerts',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='random',
            name='stats',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
