# Generated by Django 4.2.1 on 2024-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
