# Generated by Django 4.2.1 on 2024-05-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_faq_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='pdf',
        ),
        migrations.CreateModel(
            name='FaqPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='apply.faq')),
            ],
        ),
    ]
