# Generated by Django 4.2.1 on 2024-05-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0013_alter_faqpdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqPdf',
        ),
    ]
